name: Test, build and deploy

on: [push]

# Disable all permissions by default, requiring explicit permission definitions for all jobs.
permissions: {}

jobs:
  check:
    name: Lint & typecheck
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 2
          persist-credentials: false
      - name: Install correct Node.js version
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 24
      - name: Install correct pnpm version
        run: corepack enable
      - name: Enable pnpm caching (requires that correct Node.js and pnpm versions are already installed)
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          cache: pnpm
      - run: pnpm i --frozen-lockfile
      - name: Lint & typecheck
        run: |
          pnpm run typecheck
          pnpm run lint
